### PR TITLE
Update for Idris 0.12.2, WIP Effects, general tidying

### PR DESCRIPTION
**Pull request by yurrriq**
See commit messages for details. This PR (at least partially) address #7.

N.B. My usage of the Effects is likely flawed.

### CODE REVIEW

**Comment by david-christiansen** [comment]
Thanks a bunch! I'll give it a good look in the morning.

2016-08-25 22:32 GMT-04:00 Eric Bailey notifications@github.com:

**Comment by david-christiansen** [comment]
OK, so there's a few things about this that I'm not a fan of, but it's all quibbling little formatting stuff, so I'll just go ahead and tweak that on my end as part of the merge process.

**Comment by yurrriq** [comment]
Sounds good. I'll check the diff and adapt to match the style better going forward.

**Comment by yurrriq** [comment]
:+1: for `CONTRIBUTING.md`. I'll be sure to follow those guidelines for any future contributions.

**Comment by david-christiansen** [comment]
I figure that if I'm going to be picky, I should at least be so explicitly :-)

**Pull request merged**
